package ava_services

import (
	"fmt"
	"github.com/kurtosis-tech/ava-e2e-tests/commons/ava_default_testnet"
	"github.com/kurtosis-tech/kurtosis/commons/services"
	"github.com/palantir/stacktrace"
	"github.com/sirupsen/logrus"
	"os"
	"strings"
)

const (
	httpPort             = 9650
	stakingPort          = 9651
	stakingTlsCertFileId = "staking-tls-cert"
	stakingTlsKeyFileId  = "staking-tls-key"

	testVolumeMountpoint = "/shared"
)

// ========= Loglevel Enum ========================
type geckoLogLevel string
const (
	LOG_LEVEL_VERBOSE geckoLogLevel = "verbo"
	LOG_LEVEL_DEBUG   geckoLogLevel = "debug"
	LOG_LEVEL_INFO    geckoLogLevel = "info"
)

// ========= Initializer Core ========================
type GeckoServiceInitializerCore struct {
	snowSampleSize    int
	snowQuorumSize    int
	stakingTlsEnabled bool
	bootstrapperNodeIds []string
	certProvider 	GeckoCertProvider
	logLevel          geckoLogLevel
}

/*
Creates a new Gecko service initializer core with the following parameters:

Args:
	snowSampleSize: Sample size for Snow consensus protocol
	snowQuroumSize: Quorum size for Snow consensus protocol
	stakingTlsEnabled: Whether this node will use staking & TLS
	bootstrapperNodeIds: The node IDs of the bootstrapper nodes that this node will connect to. While this *seems* unintuitive
		why this would be required, it's because Gecko doesn't actually use certs. So, to prevent against man-in-the-middle attacks,
		the user is required to manually specify the node IDs of the nodese it's connecting to.
	certProvider: Provides the certs used by the Gecko services generated by this core
	logLevel: The loglevel that the Gecko node should output at.

Returns:
	An intializer core for creating Gecko nodes with the specified parameers.
 */
func NewGeckoServiceInitializerCore(
			snowSampleSize int,
			snowQuorumSize int,
			stakingTlsEnabled bool,
			bootstrapperNodeIds []string,
			certProvider GeckoCertProvider,
			logLevel geckoLogLevel) *GeckoServiceInitializerCore {
	// Defensive copy
	bootstrapperIdsCopy := make([]string, 0, len(bootstrapperNodeIds))
	copy(bootstrapperIdsCopy, bootstrapperNodeIds)
	return &GeckoServiceInitializerCore{
		snowSampleSize:    snowSampleSize,
		snowQuorumSize:    snowQuorumSize,
		stakingTlsEnabled: stakingTlsEnabled,
		bootstrapperNodeIds: bootstrapperIdsCopy,
		certProvider: certProvider,
		logLevel:          logLevel,
	}
}

func (core GeckoServiceInitializerCore) GetUsedPorts() map[int]bool {
	return map[int]bool{
		httpPort:    true,
		stakingPort: true,
	}
}

func (core GeckoServiceInitializerCore) GetFilesToMount() map[string]bool {
	if core.stakingTlsEnabled {
		return map[string]bool{
			stakingTlsCertFileId: true,
			stakingTlsKeyFileId:  true,
		}
	}
	return make(map[string]bool)
}

func (core GeckoServiceInitializerCore) InitializeMountedFiles(osFiles map[string]*os.File, dependencies []services.Service) (err error) {
	certFilePointer := osFiles[stakingTlsCertFileId]
	keyFilePointer := osFiles[stakingTlsKeyFileId]
	defaultStakers := ava_default_testnet.DefaultTestNet.DefaultStakers
	/*
		TODO TODO TODO use a TlsCertKeyProvider in order to inject identities properly
		This is a huge hack because if someone defines a dependency chain rather than
		accumulating dependencies, this whole thing breaks.
	 */
	if len(dependencies) < 5 {
		certFilePointer.WriteString(defaultStakers[len(dependencies)].TlsCert)
		keyFilePointer.WriteString(defaultStakers[len(dependencies)].PrivateKey)
	} else {

		certPEM, keyPEM, err := core.certProvider.GetCertAndKey()
		if err != nil {
			return stacktrace.Propagate(err, "Failed to write files.")
		}
		certFilePointer.Write(certPEM.Bytes())
		keyFilePointer.Write(keyPEM.Bytes())
	}
	return nil
}

func (core GeckoServiceInitializerCore) GetStartCommand(mountedFileFilepaths map[string]string, publicIpAddr string, dependencies []services.Service) ([]string, error) {
	publicIpFlag := fmt.Sprintf("--public-ip=%s", publicIpAddr)
	commandList := []string{
		"/gecko/build/ava",
		publicIpFlag,
		"--network-id=local",
		fmt.Sprintf("--http-port=%d", httpPort),
		fmt.Sprintf("--staking-port=%d", stakingPort),
		fmt.Sprintf("--log-level=%s", core.logLevel),
		fmt.Sprintf("--snow-sample-size=%d", core.snowSampleSize),
		fmt.Sprintf("--snow-quorum-size=%d", core.snowQuorumSize),
		fmt.Sprintf("--staking-tls-enabled=%v", core.stakingTlsEnabled),
	}

	if core.stakingTlsEnabled {
		certFilepath, found := mountedFileFilepaths[stakingTlsCertFileId]
		if !found {
			return nil, stacktrace.NewError("Could not find file key '%v' in the mounted filepaths map; this is likely a code bug", stakingTlsCertFileId)
		}
		keyFilepath, found := mountedFileFilepaths[stakingTlsKeyFileId]
		if !found {
			return nil, stacktrace.NewError("Could not find file key '%v' in the mounted filepaths map; this is likely a code bug", stakingTlsKeyFileId)
		}
		commandList = append(commandList, fmt.Sprintf("--staking-tls-cert-file=%s", certFilepath))
		commandList = append(commandList, fmt.Sprintf("--staking-tls-key-file=%s", keyFilepath))
	}


	// If bootstrap nodes are down then Gecko will wait until they are, so we don't actually need to busy-loop making
	// requests to the nodes
	if dependencies != nil && len(dependencies) > 0 {
		avaDependencies := make([]AvaService, 0, len(dependencies))
		for _, service := range dependencies {
			avaDependencies = append(avaDependencies, service.(AvaService))
		}

		defaultStakers := ava_default_testnet.DefaultTestNet.DefaultStakers
		socketStrs := make([]string, 0, len(avaDependencies))
		bootstrapIds := make([]string, 0, len(avaDependencies))
		// TODO Use cert provider to do this properly!!!
		for i, service := range avaDependencies {
			socket := service.GetStakingSocket()
			socketStrs = append(socketStrs, fmt.Sprintf("%s:%d", socket.GetIpAddr(), socket.GetPort().Int()))
			if i < len(defaultStakers) {
				bootstrapIds = append(bootstrapIds, defaultStakers[i].NodeID)
			}
		}
		if core.stakingTlsEnabled {
			// NOTE: This seems weird, BUT there's a reason for it: Gecko doesn't use certs, and instead relies on
			//  the user explicitly passing in the node ID of the bootstrapper it wants. This prevents man-in-the-middle
			//  attacks, just like using a cert would. Us hardcoding this bootstrapper ID here is the equivalent
			//  of a user knowing the node ID in advance, which provides the same level of protection.
			commandList = append(commandList, "--bootstrap-ids=" + strings.Join(bootstrapIds, ","))
		}
		joinedSockets := strings.Join(socketStrs, ",")
		commandList = append(commandList, "--bootstrap-ips=" + joinedSockets)
	}
	logrus.Debugf("Command list: %+v", commandList)
	return commandList, nil
}

func (core GeckoServiceInitializerCore) GetServiceFromIp(ipAddr string) services.Service {
	return GeckoService{ipAddr: ipAddr}
}

func (core GeckoServiceInitializerCore) GetTestVolumeMountpoint() string {
	return testVolumeMountpoint
}
